version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root  # доступ к docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - testnet

  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4444:4444"
    networks:
      - testnet
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=60
      - SE_SESSION_RETRY_INTERVAL=1

  chrome:
    image: selenium/node-chrome:4.21.0
    container_name: chrome
    platform: linux/amd64
    depends_on:
      - selenium-hub
    shm_size: 2g
    privileged: true
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
    networks:
      - testnet

volumes:
  jenkins_home:

networks:
  testnet:
    driver: bridge
