version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17  # Используем образ с поддержкой ARM
    platform: linux/amd64             # Форсируем работу через Rosetta 2 (если нужно)
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - testnet

  selenium-hub:
    image: seleniarm/hub:4.20.0       # Официальный образ для ARM (не SeleniumHQ!)
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - testnet

  chrome:
    image: seleniarm/node-chrome:4.20.0  # ARM-совместимый образ Chrome
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true  # Опционально для параллельных тестов
    networks:
      - testnet

volumes:
  jenkins_home:

networks:
  testnet:
    driver: bridge